[#ftl]

[@c.page title="Seznam postů"]
<h1>Seznam postů</h1>
[#list posts.content]
<table class="table">
    <thead>
    <tr>
        <th scope="col">Titulek</th>
        <th scope="col">Perex</th>
        <th scope="col">Datum publikování</th>
        <th scope="col">Autor</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    [#items as post]
    <tr>
        [#if post.published??]
        <td>${post.title}</td>
        <td>${post.perex?no_esc}</td>
        <td>${post.published?date}</td>
        <td>${post.author}</td>
        <td><a href="/post/${post.slug}">Přečíst</a></td>
        [/#if]
    </tr>
    [/#items]
    </tbody>
</table>
[#else]
<p class="fst-italic">Seznam postů je prázdný.</p>
[/#list]
[/@c.page]